### PR TITLE
30 create contact page

### PR DESCRIPTION
**Pull request by ibrahimsugun**

### CODE REVIEW

**Review by KerimCETINBAS — CHANGES_REQUESTED** [review]
please use convient logs instead of like "ananze"

**Comment by ibrahimsugun** [comment]
Comment lines deleted

**Review by KerimCETINBAS — CHANGES_REQUESTED** [review]
apps/site/src/routes/contact/+page.server.ts 13.row have console.log('ananze') consider its public and everyone can see it

**Comment by ibrahimsugun** [comment]
i deleted comments , do you still see ?

**Review by KerimCETINBAS — APPROVED** [review]

**Pull request merged**
